#!/usr/bin/make -f
#
# FIXME
# Volker Brendel,  2013
# Daniel Standage, 2014
SHELL=bash
BLASTTHREADS=1

IRODS_DIR=/iplant/home/standage/Polistes_dominula/r1.2

pdom-loci-r1.2-pot-trgs.txt:		pdom-r1.2-no-anm-hits-iloci.txt pdom-tsa-aligned-unmatched-loci.txt
					comm -12 $^ > $@

pdom-r1.2-no-anm-hits-iloci.txt:	pdom-r1.2-no-anm-hits.ids pdom-loci-r1.2-mrnamap.txt
					selex --out=1 $^ | sort | uniq > $@

pdom-r1.2-no-anm-hits.ids:		
					iget $(IRODS_DIR)/genome-annotation/$@

pdom-loci-r1.2-mrnamap.txt:		
					iget $(IRODS_DIR)/interval-loci/$@

pdom-tsa-aligned-unmatched-loci.txt:	pdom-loci-r1.2.gff3 pdom-tsa-aligned-unmatched.gff3
					bedtools intersect -a <(grep $$'\tlocus\t' pdom-loci-r1.2.gff3) -b pdom-tsa-aligned-unmatched.gff3 -wa -u \
					    | perl -ne 'm/(PdomILCr1.2-\d+)/ and print "$$1\n"' \
					    | sort | uniq > $@

pdom-loci-r1.2.gff3:		
					iget $(IRODS_DIR)/interval-loci/$@

pdom-tsa-aligned-unmatched.gff3:	pdom-tsa-r1.2-unmatched-pep.txt pdom-tsa-masked-filtered.gff3
					python align-keep.py $^ > $@

pdom-tsa-masked-filtered.gff3:	
				iget $(IRODS_DIR)/transcript-alignment/$@

pdom-tsa-r1.2.fa:		
				iget $(IRODS_DIR)/transcript-assembly/$@.gz
				gunzip $@.gz

pdom-tsa-r1.2-unmatched-pep.txt:	
					iget $(IRODS_DIR)/transcript-assembly/$@
clean:				
				rm -f pdom-loci-r1.2*.txt pdom-tsa*.txt pdom-tsa*.gff3 pdom-r1.2-no-anm-hits* pdom-loci-r1.2.fa pdom-loci-r1.2.gff3 pdom-tsa-r1.2.fa
